#!/usr/bin/env bash
# TGW NixOS installer — run from a NixOS live ISO with the repo available.
#
# Usage:
#   1. Boot NixOS ISO, partition + mount target disk at /mnt
#   2. Copy or clone this repo to /tmp/tgw-flake
#   3. Run: bash /tmp/tgw-flake/nix/tgw-install.sh [hostname]
#
# If hostname is omitted, you will be prompted.
# The script generates hardware config, commits it, then installs.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
HOSTNAME="${1:-}"

if [[ -z "$HOSTNAME" ]]; then
  read -rp "Hostname for this machine (e.g. tgw-prod, tgw-test): " HOSTNAME
fi

HARDWARE_FILE="$REPO/nix/${HOSTNAME}-hardware.nix"

echo "==> Generating hardware config for $HOSTNAME"
nixos-generate-config --root /mnt --show-hardware-config > "$HARDWARE_FILE"
echo "    Written to $HARDWARE_FILE"

echo "==> Committing hardware config"
git -C "$REPO" add "$HARDWARE_FILE"
git -C "$REPO" commit -m "feat: ${HOSTNAME}-hardware.nix — generated by nixos-generate-config"

echo "==> Installing NixOS"
nixos-install --root /mnt --flake "$REPO#${HOSTNAME}"

echo ""
echo "Done. After reboot:"
echo "  1. Pair this host in Syncthing (share: tgw-flake)"
echo "  2. Future updates: tgw-rebuild"
