#!/usr/bin/env bash
# tgw-nix-sync — populate a local flake copy for offline/emergency use.
#
# NORMAL DISTRIBUTION: use scripts/tgw-push-config.sh (nixos-rebuild --target-host).
# The flake is evaluated locally on MX and the Nix store closure is pushed directly
# to the remote host — no copy of the flake source is needed on the remote.
#
# This script exists for emergency scenarios: preparing a USB offline kit, or
# pre-positioning the flake before a machine has network access.
#
# Only the files NixOS needs to run nixos-rebuild are copied:
#   flake.nix, flake.lock, nix/
#
# Usage:
#   bash scripts/tgw-nix-sync.sh           # sync repo → dest and report
#   bash scripts/tgw-nix-sync.sh --check   # dry-run, show what would change
#
# Override destination: TGW_NIX_FLAKE_DIR=/some/path bash scripts/tgw-nix-sync.sh

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${TGW_NIX_FLAKE_DIR:-$HOME/tgw-flake}"
DRY_RUN=false

if [[ "${1:-}" == "--check" ]]; then
  DRY_RUN=true
fi

RSYNC_OPTS=(-a --delete --exclude=".git" --exclude="*.iso")
if $DRY_RUN; then
  RSYNC_OPTS+=(--dry-run --itemize-changes)
  echo "==> dry-run: changes that would be applied to $DEST"
else
  mkdir -p "$DEST"
fi

# flake.lock is generated by `nix flake update` on a Nix machine and committed
# back to the repo — skip gracefully if not yet present.
FLAKE_FILES=("$REPO/flake.nix")
[[ -f "$REPO/flake.lock" ]] && FLAKE_FILES+=("$REPO/flake.lock")

rsync "${RSYNC_OPTS[@]}" \
  "${FLAKE_FILES[@]}" \
  "$DEST/"

rsync "${RSYNC_OPTS[@]}" \
  "$REPO/nix/" \
  "$DEST/nix/"

if ! $DRY_RUN; then
  FILE_COUNT=$(find "$DEST" -type f | wc -l)
  echo "==> tgw-nix-sync: $DEST updated ($FILE_COUNT files, $(date -Iseconds))"
  echo "    For normal updates use: bash scripts/tgw-push-config.sh <hostname> <ip>"
fi
